---
- name: generate mysql root password
  shell:
    test -f /root/.my.cnf
    && (grep ^password /root/.my.cnf | head -1 | awk '{print $3}')
    || (cat /dev/urandom | tr -dc '[:alnum:]' | head -c 32)
  changed_when: False
  register: mysql_root_pass

- name: set mysql root password
  mysql_user:
    name=root
    host=localhost
    password={{ mysql_root_pass.stdout }}

- name: put .my.cnf
  template:
    src=root/.my.cnf.j2
    dest=/root/.my.cnf
    mode=600

- name: fetch .my.cnf
  fetch:
    src=/root/.my.cnf
    dest=tmp/.my.cnf
    flat=yes
  when: mysql_repl_role == "master"

- name: set mysql root password
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_pass.stdout }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: generate mysql replication user password
  shell:
    echo -n '{{ mysql_root_pass.stdout }}' | md5sum
    | awk '{print $1}'
  changed_when: False
  when: mysql_repl_role == "master"
  register: mysql_repl_pass

- name: create replication user
  mysql_user:
    name={{ mysql_repl_user }}
    password={{ mysql_repl_pass.stdout }}
    host={{ mysql_repl_net }}
    priv=*.*:"REPLICATION SLAVE"
  when: mysql_repl_role == "master"

- name: generate server-id
  shell:
    hostname -I | sed -e 's/ /\n/' | grep -v '^$'
    | tail -1 | awk -F. '{print $3 * 256 + $4}'
  changed_when: False
  register: mysql_server_id

- name: put my.cnf
  template:
    src=etc/mysql/my.cnf.j2
    dest=/etc/mysql/my.cnf
  register: last_result

- name: restart mysql
  service:
    name=mysql
    state=restarted
  when: last_result.changed

- name: export dump file
  shell:
    mysqlrepldump.sh | gzip > /tmp/mysqldump.sql.gz
  when: mysql_repl_role == "master"

- name: fetch dump file
  fetch:
    src=/tmp/mysqldump.sql.gz
    dest=tmp/mysqldump.sql.gz
    flat=yes
  when: mysql_repl_role == "master"

- name: put dump file
  copy:
    src=tmp/mysqldump.sql.gz
    dest=/tmp/mysqldump.sql.gz
  when: mysql_repl_role == "slave"

- name: check status of slaves
  mysql_replication: mode=getslave
  ignore_errors: true
  register: slave_status
  when: mysql_repl_role == "slave"

- name: stop replication
  mysql_replication: mode=stopslave
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")

- name: get mysql replication user password
  local_action:
    shell grep ^password tmp/.my.cnf | head -1 | awk '{print $3}'
    | tr -d '\n' | md5
  sudo: False
  changed_when: False
  when: mysql_repl_role == "slave"
  register: mysql_repl_pass

- name: set replication
  mysql_replication:
    mode=changemaster
    master_host={{ mysql_repl_master }}
    master_user={{ mysql_repl_user }}
    master_password={{ mysql_repl_pass.stdout }}
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")

- name: import dump file
  shell:
    zcat /tmp/mysqldump.sql.gz | mysql
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")

- name: start replication
  mysql_replication: mode=startslave
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")
