---
- name: get database root password or generate one
  shell:
    (awk -F'"' '/^password/{print $2;exit;}' /root/.my.cnf) ||
    (</dev/urandom LC_ALL=C sed -r 'N;s/[^[:print:]]|[\s"]//g' | head -c 32)
  changed_when: False
  register: mysql_root_pass

- name: set database root password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_pass.stdout }}"
  with_items:
    - ::1
    - 127.0.0.1
    - localhost # needs to be last for idempotency.

- name: remove generic database users
  mysql_user:
    name: "{{ item.user }}"
    host: "{{ item.host }}"
    state: "absent"
  with_items:
    - { user: root, host: "{{ ansible_hostname }}" }

- name: put .my.cnf
  template:
    src=root/.my.cnf.j2
    dest=/root/.my.cnf
    mode=0600

- name: fetch .my.cnf
  fetch:
    src=/root/.my.cnf
    dest=tmp/.my.cnf
    flat=yes
  when: mysql_repl_role == "master"

- name: generate database replication user password
  shell:
    echo -n '{{ mysql_root_pass.stdout }}' | md5sum | awk '{print $1}'
  changed_when: False
  when: mysql_repl_role == "master"
  register: mysql_repl_pass

- name: Ensure replication user exists on master
  mysql_user:
    name: "{{ mysql_repl_user }}"
    host: "{{ mysql_repl_net | default('%') }}"
    password: "{{ mysql_repl_pass.stdout }}"
    priv: "*.*:SELECT, PROCESS, FILE, SUPER, REPLICATION CLIENT, REPLICATION SLAVE, RELOAD"
  when: >
    mysql_repl_role == "master"
    and mysql_repl_user is defined
    and mysql_repl_master is defined

- name: generate server-id (eth0 IPv4 long)
  shell:
    ip -o -4 a s eth0 |
    awk '{sub(/\/.*/, "", $4);split($4, a, "."); print a[1]*256^3 + a[2]*256^2 + a[3]*256 + a[4]; exit}'
  changed_when: False
  register: mysql_server_id

- name: put my.cnf
  template:
    src=etc/mysql/my.cnf.j2
    dest=/etc/mysql/my.cnf
  register: last_result

- name: restart mysql
  service:
    name=mysql
    state=restarted
  when: last_result.changed

- name: export dump file
  shell:
    mysqlrepldump.sh | gzip > /tmp/mysqldump.sql.gz
  when: mysql_repl_role == "master"

- name: fetch dump file
  fetch:
    src=/tmp/mysqldump.sql.gz
    dest=tmp/mysqldump.sql.gz
    flat=yes
  when: mysql_repl_role == "master"

- name: put dump file
  copy:
    src=tmp/mysqldump.sql.gz
    dest=/tmp/mysqldump.sql.gz
  when: mysql_repl_role == "slave"

- name: check status of slaves
  mysql_replication: mode=getslave
  ignore_errors: true
  register: slave_status
  when: mysql_repl_role == "slave"

- name: stop replication
  mysql_replication: mode=stopslave
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")

- name: get mysql replication user password
  local_action:
    shell awk -F'"' '/^password/{printf "%s", $2;exit}' .my.cnf | md5sum | awk '{print $1}'
  sudo: False
  changed_when: False
  when: mysql_repl_role == "slave"
  register: mysql_repl_pass

- name: set replication
  mysql_replication:
    mode=changemaster
    master_host={{ mysql_repl_master }}
    master_user={{ mysql_repl_user }}
    master_password={{ mysql_repl_pass.stdout }}
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")

- name: import dump file
  shell:
    zcat /tmp/mysqldump.sql.gz | mysql
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")

- name: start replication
  mysql_replication: mode=startslave
  when: mysql_repl_role == "slave" and (slave_status|failed or slave_status.Slave_SQL_Running != "Yes")
