---
# Database configuration
# ######################
- name: get or generate server-id
  shell:
    ip -o -4 a s eth0 |
    awk '{sub(/\/.*/, "", $4);split($4, a, "."); print a[1]*256^3 + a[2]*256^2 + a[3]*256 + a[4]; exit}'
  changed_when: False
  register: command
  when: not mysql_server_id
- set_fact: mysql_server_id={{ command.stdout }}
  when: not mysql_server_id and command.stdout is defined


- name: get MySQL root password or generate one if none specified
  shell:
    (LC_ALL=C sed -rn 's/^[[:blank:]]*pwd[[:blank:]]*=[[:blank:]]*([\x27"]?)(.*?)(\1)[[:blank:]]*$/\2/p' /root/.my.cnf) ||
    (LC_ALL=C sed -r 'N;s/[^[:print:]]|[\x21-\x27`]//g' /dev/urandom | head -c 32)
  changed_when: False
  register: command
  when: not mysql_root_password
- set_fact: mysql_root_password={{ command.stdout }}
  when: not mysql_root_password and command.stdout is defined


- name: configure database server
  template:
    src: 'etc/mysql/conf.d/mysqld.cnf.j2'
    dest: '/etc/mysql/conf.d/mysqld.cnf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'reload MySQL' ]


- name: create slow query log file
  file:
    state=touch
    path={{ mysql_slow_query_log_file }}
    owner=mysql
    group=mysql
    mode=0644
  when: mysql_slow_query_log_file


- name: database replication configuration
  include: 'configure_replication.yml'
  tags:
    - mysql/replication


- name: auto MySQL backup configuration
  include: 'configure_automysqlbackup.yml'
  tags:
    - mysql/backup
  when: mysql_backup and mysql_register_version is defined
