---
# Replication
# ###########
- name: ensure replication user exists on master
  mysql_user:
    name: "{{ mysql_replication_user_name }}"
    host: "{{ mysql_replication_user_host }}"
    password: "{{ mysql_replication_user_pass }}"
    priv: "{{ mysql_replication_user_priv }}"
  when: >
    mysql_replication_master
    and mysql_replication_role == "master" and mysql_replication_user_name
    and mysql_replication_user_pass


- name: check slave replication status
  mysql_replication: mode=getslave
  ignore_errors: true
  register: slave
  when: mysql_replication_role == "slave" and mysql_replication_master

- name: check master replication status
  mysql_replication: mode=getmaster
  delegate_to: "{{ mysql_replication_master }}"
  register: master
  when:
        mysql_replication_role == "slave"
    and mysql_replication_master != ""
    and slave|failed

- name: configure replication on the slave
  mysql_replication:
    mode: changemaster
    master_host: "{{ mysql_replication_master }}"
    master_user: "{{ mysql_replication_user_name }}"
    master_password: "{{ mysql_replication_user_pass }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: True
  when:
        mysql_replication_role == "slave"
    and mysql_replication_master != ""
    and mysql_replication_user
    and slave|failed

- name: start replication
  mysql_replication: mode=startslave
  when:
        mysql_replication_role == "slave"
    and mysql_replication_master != ""
    and slave|failed
