---
# innobackupex --defaults-file=/etc/mysql/my.cnf --user=DBUSER --password=DBUSERPASS /path/to/BACKUP-DIR/ no-timestamp
- name: 'xtrabackup: create backup directory'
  file:
    path: "{{ mysql_xtrabackup_options.BACKUPDIR }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'
  when:
        mysql_xtrabackup
    and mysql_xtrabackup_options.BACKUPDIR|default()

- name: 'xtrabackup: install a helper'
  template:
    src: 'usr/local/sbin/xtrabackup_helper.j2'
    dest: '/usr/local/sbin/xtrabackup_helper'
    owner: 'root'
    group: 'root'
    mode: 0755
  when: mysql_xtrabackup

- name: 'xtrabackup: install a cron job'
  template:
    src: 'etc/cron.d/xtrabackup.j2'
    dest: '/etc/cron.d/xtrabackup'
    owner: root
    group: root
    mode: 0640
  when: mysql_xtrabackup
