---
# XXX: only Debian for now, in the future will probably be something like:
# - include: "install_for_{{ ansible_os_family }}.yml"
- name: check if database server is installed
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'mariadb-server' 'mysql-server' 'percona-server-server' | grep -v '^$'
  register: mysql_register_version
  changed_when: False
  failed_when: False

#XXX: only MySQL for now
- name: install MySQL on Debian
  apt:
    name: '{{ item }}'
    install_recommends: False
  with_flattened:
    - mysql_packages_map[mysql_vendor]
    - [ '{{ "automysqlbackup" if mysql_backup|default() else [] }}' ]
  register: mysql_register_install_status

- name: ensure /etc/mysql/conf.d existance
  file:
    path: /etc/mysql/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure /etc/mysql/conf.d inclusion
  lineinfile:
    dest: '{{ "/etc/mysql/my.cnf" if ansible_os_family == "Debian" else "/etc/my.cnf" }}'
    line: "!includedir /etc/mysql/conf.d/"

- name: configure database client on first install
  template:
    src: 'etc/mysql/conf.d/client.cnf.j2'
    dest: '/etc/mysql/conf.d/client.cnf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: mysql_register_version|default() and not mysql_register_version.stdout

- name: database configuration
  include: 'configuration.yml'
  tags:
    - mysql/configuration

- name: restart database server on first install
  service:
    name: 'mysql'
    state: 'restarted'
  when:
    (mysql_register_install_status|default() and mysql_register_install_status.changed)
    and (mysql_register_version|default() and not mysql_register_version.stdout)

- name: secure installation
  include: 'secure_installation.yml'
  tags:
    - mysql/secure_installation

- name: create a fact directory on the target machine
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: save facts on the machine
  template:
    src: 'etc/ansible/facts.d/mysql.fact.j2'
    dest: '/etc/ansible/facts.d/mysql.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: mysql_register_facts_locally

- name: reload facts if they have changed
  action: setup
  when: mysql_register_facts_locally|default() and mysql_register_facts_locally.changed

