---
- name: restart database server on first install
  service:
    name: 'mysql'
    state: 'restarted'

- name: find unnecessary accounts
  command:
    mysql -NBe 'SELECT User, Host FROM mysql.user WHERE (User="root" AND Host!="localhost") OR User="";'
  changed_when: False
  register: command

- name: show unnecessary accounts
  debug: var=command.stdout_lines
  when: command.stdout is defined

- name: drop unnecessary accounts
  mysql_user:
   name: "{{ item.split('\t').0 }}"
   host: "{{ item.split('\t').1 }}"
   state: 'absent'
  with_items: command.stdout_lines
  when: command.stdout is defined

- name: remove test database on first install
  mysql_db:
    db: test
    state: absent
  when: mysql_register_install_status.changed is defined

