---
- name: find unnecessary accounts
  command:
    mysql -NBe 'SELECT User, Host FROM mysql.user WHERE (User="root" AND Host!="localhost") OR User="";'
  changed_when: False
  register: command

- name: drop unnecessary accounts
  mysql_user:
   name: "{{ item.split('\t').0 }}"
   host: "{{ item.split('\t').1 }}"
   state: 'absent'
  with_items: command.stdout_lines
  when: command.stdout is defined

- name: update database admin password
  mysql_user:
    name: 'root'
    host: 'localhost'
    password: '{{ mysql_root_password }}'

- name: create /root/.my.cnf with root credentials
  template:
    src: 'root/my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: remove test database on first install
  mysql_db:
    db: test
    state: absent
  when:
        mysql_register_install_status.changed is defined
    and mysql_register_version.stdout is not defined

