#!/bin/bash
# {{ ansible_managed }}


INCREMENTAL=
BACKUP_DIR="{{ mysql_xtrabackup_options.BACKUP_DIR }}"
OPTS="mysql_xtrabackup_options.HELPER_OPTS"




usage()
{
	echo "$(basename $0) - [OPTIONS]"
	echo
	echo '  -h       this help'
	echo "  -d PATH  backup directory (default: $BACKUP_DIR)"
	echo '  -i       make an incremental backup'
	echo "  -o OPTS  additionnal options passed to innobackupex (default: $OPTS)"
	echo
}





GETOPT=$(getopt -o hid:o: -n "$0" -- "$@") || exit 1
eval set -- $GETOPT
while true;do
	case "$1" in
	--)
		shift
		break
		;;
	-h)
		usage
		exit
		;;
	-i)
		INCREMENTAL=1
		shift
		;;
	-d)
		BACKUP_DIR="$2"
		shift 2
		;;
	-o)
		OPTS="$2"
		shift 2
		;;
	esac
done



if [ -z "$INCREMENTAL" ]
then
	innobackupex "$BACKUP_DIR" $OPTS 2>&1
else
	INCREMENTAL_BASEDIR=$(ls -v "$BACKUP_DIR" | tail -1)
	if [ -z "$INCREMENTAL_BASEDIR" ]
	then
		echo "Error: unable to find a previous backup to increment" >&2
		exit 1
	fi
	innobackupex "$BACKUP_DIR" $OPTS --incremental --incremental-basedir="$INCREMENTAL_BASEDIR" 2>&1
fi
