---
# XXX: currently unused
- name: add MariaDB APT GPG key
  apt_key:
    state: present
    id: "0xcbcb082a1bb943db"
    keyserver: 'hkp://keyserver.ubuntu.com:80'
  when: mysql_flavor == 'MariaDB-upstream'

- name: add MariaDB APT repository
  apt_repository:
    repo: '{{ mariadb_server_upstream_repository }}' # XXX?
    state: 'present'
    update_cache: True
  when: mysql_flavor == 'MariaDB-upstream'

# see https://downloads.mariadb.org/mariadb/repositories/
- apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db
- apt_repository: repo='deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu trusty main'
  ignore_errors: True
  register: mariadb_repository_added
- name: install MariaDB
  apt:
    name=mariadb-server
    update_cache=yes
    install_recommends=no
  register: mariadb_installed
